name: Build Vite project, package into zip file, and upload.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Package into zip file
        run: zip -r my-project.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-project
          path: my-project.zip